@startwbs
title トレーサビリティ・ダイアグラム (BUC_01: 日々のタスクを登録し、管理する)

* **BUC_01: 日々のタスクを登録し、管理する**
** **AFL_01: 業務フロー**
*** **ACT_01: タスクの登録**
**** **SUC_01: タスクを登録する**
***** ENT_01: タスク (Create)
***** STA_01: 状態を「未完了」へ
***** SCR_01: タスク一覧画面
***** SCR_02: タスク登録画面
*** **ACT_02: タスクの確認と更新**
**** **SUC_02: タスクを更新する**
***** ENT_01: タスク (Update)
***** SCR_03: タスク編集画面
**** **SUC_04: タスク一覧を表示する**
***** ENT_01: タスク (Read)
***** SCR_01: タスク一覧画面
*** **ACT_03: タスクの完了**
**** **SUC_03: タスクを完了する**
***** ENT_01: タスク (Update)
***** STA_01: 状態を「完了」へ
@endwbs
