import { Box, CssBaseline } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <CssBaseline />
      <body
        style={{
          backgroundColor: "#f5f5f5",
          padding: "10px",
        }}
      >
        <Box
          sx={{
            maxWidth: "1024px",
            margin: "0 auto",
            paddingTop: 1,
            paddingBottom: 1,
          }}
        >
          {children}
        </Box>
      </body>
    </html>
  );
}
